### PR TITLE
Enhancement: Added Image Services to the available layers.

### PR DESCRIPTION
**Pull request by tmcgee**
Additional Clean up:
1. Removed unnecessary `require(modules` since the modules are
   already included at the top
2. Removed 2 console.log statements
3. Removed 'topic.publish` for google analytics widget.
4. Reformatting and indenting of code

### CODE REVIEW

**Comment by tmcgee** [comment]
I just now noticed that these modules are not used and can be removed:

- Form,
- FilteringSelect,
- HorizontalSlider,
- HorizontalRule,
- HorizontalRuleLabels,
- Select,
- topic (because it is no longer publishing)

I can remove them in a separate PR (or you can). Due to the removal of `topic`, that 2nd PR probably makes more sense after merging this PR if you deem it worthy.

**Comment by tmcgee** [comment]
On second thought, they are probably used are in the html template. In that case, they don't need to be listed as arguments for the function in the JS file.

**Comment by jebu75** [comment]
Thanks @tmcgee!  I think this one of my very first CMV widgets.  Interesting to look back and see how obviously new to Dojo I was.

I will probably add the the `topic` dependency back to publish the googleAnalytics events but will look at making sending of events configurable or add that functionality back in via an optional mixin.  Any reason in particular you removed it?

**Comment by tmcgee** [comment]
I removed those lines for no particular reason other than my own clarity while inspecting the code to add this enhancement. "making the sending of events configurable" is a good objective. I think an approach like that would be very useful for a lot of current and future widgets.

**Pull request merged**
